const mongoose = require('mongoose');

// Feature Schema - Feature selection with optional spec value
const featureSchema = new mongoose.Schema({
  featureId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'FeatureType',
    required: true
  },
  spec: {
    type: String,
    trim: true,
    default: ''
  }
}, { _id: false });

// Custom Specification Item Schema
const customSpecificationItemSchema = new mongoose.Schema({
  name: {
    type: String,
    required: true,
    trim: true
  },
  specification: {
    type: String,
    required: true,
    trim: true
  }
}, { _id: false });

// Custom Specification Category Schema
const customSpecificationCategorySchema = new mongoose.Schema({
  category: {
    type: String,
    required: true,
    trim: true
  },
  items: [customSpecificationItemSchema]
}, { _id: false });

// Drawing Specification Schema
const drawingSpecificationSchema = new mongoose.Schema({
  // Auto-generated composite key: BODYTYPE/CHASSIS/CHASSISMODEL/SIZE/DIMENSION/FEATURE1_SPEC-FEATURE2_SPEC-...
  // Made optional in schema - generated by pre-save hook before validation
  drawingNumber: {
    type: String,
    required: false, // Will be set by pre-save hook
    unique: true,
    trim: true,
    uppercase: true,
    index: true
  },
  
  // Master table references
  bodyTypeId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'BodyType',
    required: true,
    index: true
  },
  
  // Optional fields per new requirements
  chassisTypeId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'ChassisType',
    required: false,
    index: true
  },
  
  chassisModel: {
    type: String,
    required: false,
    trim: true,
    default: ''
  },
  
  sizeTypeId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'SizeType',
    required: false,
    index: true
  },
  
  // Dimension as a single plain string (optional per new requirements)
  dimension: {
    type: String,
    required: false,
    trim: true,
    default: ''
  },
  
  // Features array - each feature has featureId and optional spec
  features: [featureSchema],
  
  // Custom specifications - category-based specifications specific to this drawing
  customSpecifications: [customSpecificationCategorySchema],
  
  // GridFS file reference (single file) - DWG/DXF only, compressed before storage
  drawingFile: {
    fileId: {
      type: mongoose.Schema.Types.ObjectId,
      required: false
    },
    filename: {
      type: String,
      required: false
    },
    originalName: {
      type: String,
      required: false
    },
    uploadedFormat: {
      type: String,
      enum: ['DWG', 'DXF'],
      required: false
    },
    storedFormat: {
      type: String,
      enum: ['DXF', 'DWG'], // Allow DWG if conversion not available
      required: false,
      default: 'DXF'
    },
    originalFileSize: {
      type: Number,
      required: false
    },
    compressedFileSize: {
      type: Number,
      required: false
    },
    isCompressed: {
      type: Boolean,
      default: true
    },
    uploadDate: {
      type: Date,
      default: Date.now
    }
  },
  
  // User tracking
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  
  lastModifiedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  }
}, {
  timestamps: true
});

// Helper function to normalize key segments (UPPERCASE, remove spaces and slashes)
const normalizeKeySegment = (str) => {
  if (!str) return '';
  return String(str)
    .trim()
    .toUpperCase()
    .replace(/\s+/g, '')
    .replace(/\//g, '')
    .replace(/-/g, '');
};

// Helper function to format features for composite key
const formatFeatures = (features) => {
  if (!features || features.length === 0) return '';
  
  return features
    .map(feature => {
      if (!feature.featureId) return null;
      // Get feature shortName if populated, otherwise use featureId
      const featureKey = feature.featureId.shortName || feature.featureId.toString();
      const specValue = feature.spec ? normalizeKeySegment(feature.spec) : '';
      return specValue ? `${normalizeKeySegment(featureKey)}_${specValue}` : normalizeKeySegment(featureKey);
    })
    .filter(Boolean)
    .join('-');
};

// Pre-save middleware to generate composite key
drawingSpecificationSchema.pre('save', async function(next) {
  try {
    // Populate references if not already populated
    await this.populate([
      { path: 'bodyTypeId', select: 'shortName name' },
      { path: 'chassisTypeId', select: 'shortName name' },
      { path: 'sizeTypeId', select: 'shortName name' },
      { path: 'features.featureId', select: 'shortName name' }
    ]);
    
    // Build composite key segments
    const bodyTypeKey = this.bodyTypeId?.shortName || this.bodyTypeId?.toString() || '';
    const chassisKey = this.chassisTypeId?.shortName || this.chassisTypeId?.toString() || '';
    const chassisModelKey = normalizeKeySegment(this.chassisModel || '');
    const sizeKey = this.sizeTypeId?.shortName || this.sizeTypeId?.toString() || '';
    const dimensionKey = normalizeKeySegment(this.dimension || '');
    const featuresKey = formatFeatures(this.features);
    
    // Build composite key: BODYTYPE/CHASSIS/CHASSISMODEL/SIZE/DIMENSION/FEATURE1_SPEC-FEATURE2_SPEC-...
    // Only include segments that have values
    const keyParts = [normalizeKeySegment(bodyTypeKey)]; // Always required
    
    if (chassisKey) keyParts.push(chassisKey);
    if (chassisModelKey) keyParts.push(chassisModelKey);
    if (sizeKey) keyParts.push(normalizeKeySegment(sizeKey));
    if (dimensionKey) keyParts.push(dimensionKey);
    if (featuresKey) keyParts.push(featuresKey);
    
    this.drawingNumber = keyParts.join('/');
    next();
  } catch (error) {
    next(error);
  }
});

// Pre-update middleware to regenerate composite key on updates
drawingSpecificationSchema.pre(['findOneAndUpdate', 'updateOne', 'findByIdAndUpdate'], async function(next) {
  try {
    const update = this.getUpdate() || {};
    const updateData = update.$set || update;
    
    // Only regenerate key if relevant fields are being updated
    const relevantFields = ['bodyTypeId', 'chassisTypeId', 'chassisModel', 'sizeTypeId', 'dimension', 'features'];
    const hasRelevantChanges = relevantFields.some(field => updateData.hasOwnProperty(field));
    
    if (hasRelevantChanges) {
      // Get the current document
      const currentDoc = await this.model.findOne(this.getQuery()).lean();
      if (currentDoc) {
        // Merge current doc with updates
        const mergedDoc = {
          ...currentDoc,
          ...updateData
        };
        
        // Fetch populated references for the merged data
        const BodyType = mongoose.model('BodyType');
        const ChassisType = mongoose.model('ChassisType');
        const SizeType = mongoose.model('SizeType');
        const FeatureType = mongoose.model('FeatureType');
        
        const [bodyType, chassisType, sizeType] = await Promise.all([
          mergedDoc.bodyTypeId ? BodyType.findById(mergedDoc.bodyTypeId).select('shortName name').lean() : null,
          mergedDoc.chassisTypeId ? ChassisType.findById(mergedDoc.chassisTypeId).select('shortName name').lean() : null,
          mergedDoc.sizeTypeId ? SizeType.findById(mergedDoc.sizeTypeId).select('shortName name').lean() : null
        ]);
        
        // Fetch feature types if features are updated
        let populatedFeatures = mergedDoc.features || [];
        if (mergedDoc.features && Array.isArray(mergedDoc.features) && mergedDoc.features.length > 0) {
          const featureIds = mergedDoc.features.map(f => f.featureId).filter(Boolean);
          if (featureIds.length > 0) {
            const featureTypes = await FeatureType.find({ _id: { $in: featureIds } }).select('shortName name').lean();
            const featureMap = new Map(featureTypes.map(ft => [ft._id.toString(), ft]));
            populatedFeatures = mergedDoc.features.map(f => ({
              ...f,
              featureId: featureMap.get(f.featureId?.toString() || f.featureId) || f.featureId
            }));
          }
        }
        
        // Build composite key - only include segments with values
        const bodyTypeKey = bodyType?.shortName || mergedDoc.bodyTypeId?.toString() || '';
        const chassisKey = chassisType?.shortName || mergedDoc.chassisTypeId?.toString() || '';
        const chassisModelKey = normalizeKeySegment(mergedDoc.chassisModel || '');
        const sizeKey = sizeType?.shortName || mergedDoc.sizeTypeId?.toString() || '';
        const dimensionKey = normalizeKeySegment(mergedDoc.dimension || '');
        const featuresKey = formatFeatures(populatedFeatures);
        
        const keyParts = [normalizeKeySegment(bodyTypeKey)]; // Always required
        
        if (chassisKey) keyParts.push(chassisKey);
        if (chassisModelKey) keyParts.push(chassisModelKey);
        if (sizeKey) keyParts.push(normalizeKeySegment(sizeKey));
        if (dimensionKey) keyParts.push(dimensionKey);
        if (featuresKey) keyParts.push(featuresKey);
        
        // Set the new drawing number in update
        if (update.$set) {
          update.$set.drawingNumber = keyParts.join('/');
        } else if (!update.$set) {
          this.set({ drawingNumber: keyParts.join('/') });
        }
      }
    }
    
    next();
  } catch (error) {
    next(error);
  }
});

// Indexes for better performance
drawingSpecificationSchema.index({ drawingNumber: 1 }, { unique: true });
drawingSpecificationSchema.index({ bodyTypeId: 1 });
drawingSpecificationSchema.index({ chassisTypeId: 1 });
drawingSpecificationSchema.index({ sizeTypeId: 1 });
drawingSpecificationSchema.index({ createdBy: 1 });

// Static method to find by body type
drawingSpecificationSchema.statics.findByBodyType = function(bodyTypeId) {
  return this.find({ bodyTypeId: bodyTypeId });
};

// Static method to find by chassis type
drawingSpecificationSchema.statics.findByChassisType = function(chassisTypeId) {
  return this.find({ chassisTypeId: chassisTypeId });
};

// Static method to find by size type
drawingSpecificationSchema.statics.findBySizeType = function(sizeTypeId) {
  return this.find({ sizeTypeId: sizeTypeId });
};

module.exports = mongoose.model('DrawingSpecification', drawingSpecificationSchema);
